### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by SnonSS** [voidpointer0x00/VoidWhitelist#10]
It would be nice if you could add placeholders so that you can see how much is left to sit in the temporary whitelist

**Comment by voidpointer0x00** [comment]
Hello :)

Do you mean PlaceholderAPI support?

**Comment by SnonSS** [comment]
Yes

**Comment by voidpointer0x00** [comment]
Alright, I check the build myself and it actually works.
![image](https://user-images.githubusercontent.com/43143315/224986871-b098486e-f997-4b34-9caf-1966a7d726a7.png)
