### ISSUE TITLE
Velocity support

### ISSUE THREAD

**Issue by nsvk13** [voidpointer0x00/VoidWhitelist#13]
I use a bunch of servers: LimboAPI/LibmoAuth + Velocity + SMP server.

I can not add players from the pirate, and also, when you add a player or use , the console starts spamming with errors.
I attach pastebin: https://pastebin.com/1bBH5AiR

**Comment by voidpointer0x00** [comment]
Most of exceptions are unrelated, you really should dig into ProtocolLib/Floodgate/Netty or ask someone to help manage those errors. 

I can see you're using floodgate which is not supported on 0.8.2b405-stable, try using the latest https://github.com/voidpointer0x00/VoidWhitelist/releases/tag/v0.9.0-unstable build. 

As for Whitelist related issues, I see `/whitelist info` seems to fail when issued without arguments, I'll check that.
Also tab completion fails on `/whitelist import-json ` _(exactly with the space at the end)_ asking for an option that starts with a dash symbol `-`, that's weird, I'll check it. 

I'm asking you to run the latest build and tell if there're more errors

**Comment by voidpointer0x00** [comment]
Update on bugs, I can confirm that `/whitelist import-json` really does produce weird option bug and `/whitelist info` produces index out of bounds exception on tab complete, I'll fix it in a few hours.

Regarding your problem not being able to add an offline _(pirate)_ player — it still does work for me. What commands do you use? The command `/whitelist add` takes in a player's nickname **and** an option indicating the online/offline/bedrock status of the selected account.

So issuing `/whitelist add _voidpointer --online` and `/whitelist add _voidpointer --offline` will add different UUID entries
```json
  "whitelist": [
    {
      "uniqueId": "3d6e6616-8029-3e86-8d40-8b5bbbd0cc2a",
      "name": "_voidpointer",
      "expiresAt": null
    },
    {
      "uniqueId": "c55a15b5-896f-4c09-9c07-75ad36572aad",
      "name": "_voidpointer",
      "expiresAt": null
    }
  ]
```

**Comment by voidpointer0x00** [comment]
This update [v0.9.1-stable](https://github.com/voidpointer0x00/VoidWhitelist/releases/tag/v0.9.1-stable) should fix the addressed issued. Please, comment whether it works for you or not, otherwise I'll just close the issue myself in a few days.

**Comment by nsvk13** [comment]
Hello, yes I had some problem because of the ProtocolLib, I put it in the log by mistake. 
We had an emergency move to another plugin, I will try to do a little technical work in the evening to test the updated build of Voidwhitelist. 

PS: And we don't even need GeyserMC/Floodgate anymore, we uninstalled it and don't plan to install it anymore. :D

**Comment by voidpointer0x00** [comment]
Hey there, @HarismaLZT :)
> I will try to do a little technical work in the evening to test the updated build of Voidwhitelist.

Any news?

**Comment by nsvk13** [comment]
Sorry, we had to give up the whitelist.
