### ISSUE TITLE
/whitelist import-db not working (Purpur/Paper Server)

### ISSUE THREAD

**Issue by LandOfPeeps** [voidpointer0x00/VoidWhitelist#28]
Not sure if this is supposed to be happening but doing /whitelist import-db simply returns "Import is only available from json to database"

I did not do any changes to the database.

**Comment by voidpointer0x00** [comment]
Could you please provide the storage configuration, the list of files within the `plugins/VoidWhitelist` directory and tell what exactly you're trying to achieve with `/whitelist import-db` command?

**Comment by voidpointer0x00** [comment]
I see, I can confirm that `/whitelist import-json` does not work as expected when using JSON storage method :)

I'll look into and likely fix this evening.

**Comment by voidpointer0x00** [comment]
Oh, I'm completely wrong :rofl: 
You're supposed to import local JSON file into the currently connected database using `/whitelist import-json` command.
The `/whitelist export-db` exports all data from the current database connection into a JSON file _(that you can use just as JSON storage method, as a backup or import later)_.

**Comment by LandOfPeeps** [comment]
> Oh, I'm completely wrong 🤣 You're supposed to import local JSON file into the currently connected database using `/whitelist import-json` command. The `/whitelist export-db` exports all data from the current database connection into a JSON file _(that you can use just as JSON storage method, as a backup or import later)_.

That's what I was trying to do with that command yeah, I am trying to import my whitelist.json to your plugin's whitelist.json. I thought I could try to paste it manually as an alternative though but you seem to use a different structure for the json

**Comment by voidpointer0x00** [comment]
The command does not accept any different formats

You may be able to convert it via some scripts. Or share the file, I'll try to convert it 😄
