### ISSUE TITLE
Is there anyway to use voidwhitelist without using duration

### ISSUE THREAD

**Issue by Sobble2546** [voidpointer0x00/VoidWhitelist#30]
because when i do /whitelist information it said my whitelist is going to expire in 19 march
is there anyway to disable this

**Comment by voidpointer0x00** [comment]
As far as I remember, if you don't specify the duration using the `add` command, the plugin will add a player permanently without any duration, the add command code looks valid.

Try checking online/offline uuids, maybe you're requesting the wrong one?

**Comment by Sobble2546** [comment]
no i didnt give any duration but it still says in the information (/whitelist info <player>) there is a duration
i also specified if is it online/offline

**Comment by Sobble2546** [comment]
![image](https://github.com/voidpointer0x00/VoidWhitelist/assets/89291105/7db61a92-e3a5-47d5-a74a-05d4987501dc)
this player dosent have any set duration

**Comment by voidpointer0x00** [comment]
So what are the exact commands you used? Could you please also provide the plugin configuration, specifically online/offline section?

**Comment by Sobble2546** [comment]
i used ```/whitelist add sobble6466 -offline```
i didnt understand what u ment by configuration

**Comment by voidpointer0x00** [comment]
The yml configs in plugins/VoidWhitelist directory

Does the `/whitelist info -offline` also show player'a duration?

**Comment by Sobble2546** [comment]
Nvm I think I fixed it I turned off auto whitelist (auto whitelist somehow let a random guy joined the server) it is fixed now.
sorry for wasting ur time I didnt know there was something like auto whitelist Im really sorry for being a stupid guy.
