### ISSUE TITLE
How to add a bedrock player (who has spaces)

### ISSUE THREAD

**Issue by Sobble2546** [voidpointer0x00/VoidWhitelist#31]
I have their xuid / uid

**Comment by Sobble2546** [comment]
just to be clear floodgate adds _ for the people who has spaces
ex - sussy man floodgate change it to sussy_man

**Comment by voidpointer0x00** [comment]
You can either just write it in `whitelist.json` if mot using database or use `/whitelist add --xuid gametag`

**Comment by Sobble2546** [comment]
![image](https://github.com/voidpointer0x00/VoidWhitelist/assets/89291105/53c67090-a4fb-4f4e-94ed-5ded99a93e16)
didnt work
```
whitelist add -xuid Nyx Estellar
[18:28:21 INFO]: Invalid date-time format. A valid example for 1 day, 15 hours and 45 minutes 1d15h45m
```

**Comment by voidpointer0x00** [comment]
Wrap gametag as a whole string `"Game Tag"`

**Comment by Sobble2546** [comment]
didnt work same issue

**Comment by voidpointer0x00** [comment]
To be clear, I'm myself not sure what the gametag is, it's just what Floodgate specifies in the API: https://repo.opencollab.dev/javadoc/maven-snapshots/org/geysermc/floodgate/api/2.2.2-SNAPSHOT

**Comment by Sobble2546** [comment]
hmm i will try adding her using uuid (https://www.cxkes.me/xbox/xuid) in the data base wish me luck

**Comment by voidpointer0x00** [comment]
That's super weird why it is not accepting the gametag and thinks there's a date specified, not sure why — gonna have to debug that behavior

**Comment by Sobble2546** [comment]
aint working i thought to follow this [reddit](https://www.reddit.com/r/Minecraft/comments/qvar6j/how_to_find_xuiduuid_for_bedrock_players/) post but its soo different from the uids stored in `whitelist.json`

**Comment by voidpointer0x00** [comment]
Maybe try just specifying the username that they've logged in with? Like `/whitelist add --xuid nick_name`

The info command with the `--xuid` tag would tell what uuid was used I believe

**Comment by Sobble2546** [comment]
i tried that didnt work cuz floodgate just shits itself

**Comment by Sobble2546** [comment]
![image](https://github.com/voidpointer0x00/VoidWhitelist/assets/89291105/82de256f-fa3f-45ef-a0b5-83bc8eeafd4e)
she has agreed to change to her usertag
soo imma close this issue
but if u want fix this issue u can
